- src/main/java/com/team05/linkup/LinkupApplication.java
- src/main/java/com/team05/linkup/domain/community/api/CommunityController.java
- src/main/java/com/team05/linkup/domain/community/application/CommunityService.java
- src/main/java/com/team05/linkup/domain/community/domain/Comment.java
- src/main/java/com/team05/linkup/domain/community/domain/Community.java
- src/main/java/com/team05/linkup/domain/community/domain/CommunityCategory.java
- src/main/java/com/team05/linkup/domain/community/dto/CommunitySummaryResponse.java
- src/main/java/com/team05/linkup/domain/community/infra/CommunityRepository.java
- 커뮤니티 게시글 조회 관련 API, Service, Repository, Entity, DTO 구현
- 기능: 카테고리별/전체 목록 조회 (페이징, 정렬), 인기 게시글 조회, 키워드 검색 기능 추가
- **`CommunityController`**:
- `/v1/community/list`: 카테고리 필터링 및 페이징/정렬 가능한 게시글 목록 조회 API 추가.
- `/v1/community/popular`: 지정된 기간 내 인기 게시글 목록 조회 API 추가 (limit, day 파라미터).
- `/v1/community/more-detail`: 키워드를 이용한 게시글 검색 API 추가 (페이징, 정렬).
- **`CommunityService`**:
- `findCommunities`: Controller 요청을 받아 Repository의 목록 조회 메소드 호출.
- `findPopularCommunities`: 기간 계산 및 Repository의 인기 게시글 조회 메소드 호출.
- `searchCommunities`: Controller 요청을 받아 Repository의 키워드 검색 메소드 호출 (null/blank 체크 포함).
- 클래스 레벨 `@Transactional(readOnly = true)` 적용으로 조회 성능 최적화.
- **`Community`, `Comment` Entities**:
- 게시글(`Community`) 및 댓글(`Comment`) 엔티티 정의.
- `Community`는 `User`와 Lazy Loading 관계 설정.
- `Comment`는 `User`, …
> [feat] - 커뮤니티 목록, 인기글, 검색 조회 기능

- build.gradle
- src/main/java/com/team05/linkup/common/application/JwtServiceImpl.java
- src/main/java/com/team05/linkup/common/application/RefreshTokenService.java
- src/main/java/com/team05/linkup/common/application/RefreshTokenServiceImpl.java
- src/main/java/com/team05/linkup/common/config/SecurityConfig.java
- src/main/java/com/team05/linkup/common/filter/JwtAuthenticationFilter.java
- src/main/java/com/team05/linkup/common/util/ApiUtils.java
- src/main/java/com/team05/linkup/common/util/JwtUtils.java
- src/main/java/com/team05/linkup/domain/enums/ActivityTime.java
- src/main/java/com/team05/linkup/domain/enums/Role.java
- src/main/java/com/team05/linkup/domain/mentoring/api/AiMatchingController.java
- src/main/java/com/team05/linkup/domain/mentoring/dto/AiMatchingRequestDTO.java
- src/main/java/com/team05/linkup/domain/mentoring/dto/AiMatchingResponseDTO.java
- src/main/java/com/team05/linkup/domain/mentoring/service/AIMatchingServiceImpl.java
- src/main/java/com/team05/linkup/domain/mentoring/service/MatchingService.java
- src/main/java/com/team05/linkup/domain/mentoring/service/MatchingServiceImpl.java
- src/main/java/com/team05/linkup/domain/user/api/AuthController.java
- src/main/java/com/team05/linkup/domain/user/api/ProfileController.java
- src/main/java/com/team05/linkup/domain/user/application/MenteeProfileService.java
- src/main/java/com/team05/linkup/domain/user/application/ModifyRoleServiceImpl.java
- src/main/java/com/team05/linkup/domain/user/application/ProfileService.java
- src/main/java/com/team05/linkup/domain/user/domain/RefreshToken.java
- src/main/java/com/team05/linkup/domain/user/infrastructure/RefreshTokenRepository.java
- src/main/java/com/team05/linkup/domain/user/infrastructure/UserRepository.java
- src/main/resources/application.yml
- 리프레시 토큰 로직 수정, ai 매칭 기능 추가
- 작업 1: ai 매칭 추천 로직을 구현했습니다
- 작업 2: 리프레시 토큰 발급 로직을 수정했습니다. 기존 로직은 엑세스 토큰이 만료되면 발급받을 수 없었지만, 현재 로직은 리프레시 토큰이 만료가 됐고, sign이 valid하다면 발급받도록 수정했습니다
- 작업 3: 토큰 claim에 provider을 담아 providerAndproviderId 로 쿼리를 날려 구글과 카카오가 providerId가 겹치는 경우를 고려하여 기능을 개선햇습니다.
- (선택사항)
> [feat] ai 매칭 추천 기능 && [fix] 리프레시 토큰 로직 수정

- src/main/java/com/team05/linkup/domain/community/api/LikeController.java
- src/main/java/com/team05/linkup/domain/community/application/LikeService.java
- src/main/java/com/team05/linkup/domain/community/dto/LikeStatusResponse.java
- 커뮤니티 게시글 '좋아요' 기능을 단일 토글(Toggle) API 방식으로 리팩토링했습니다. (기존 추가/삭제 API 통합)
- 사용자는 `POST /like` 엔드포인트 하나로 '좋아요' 상태를 변경하고, 변경된 최종 상태를 응답받습니다.
- 게시글의 `likeCount`는 실시간으로 업데이트됩니다.
**1. 좋아요 기능 리팩토링:**
- **`LikeStatusResponse.java` (DTO 추가):**
- '좋아요' 토글 API의 응답 형식을 위한 `LikeStatusResponse` record DTO 추가 (`boolean liked` 필드 포함).
- **`LikeService.java` (Service 리팩토링):**
- 기존 `addLike`, `removeLike` 메소드 제거.
- `toggleLike` 메소드 구현:
- `User`, `Community` 엔티티 조회.
- `LikeRepository.findByUserAndCommunity`로 기존 '좋아요' 상태 확인.
- 상태에 따라 `Like` 레코드 생성 또는 삭제 수행.
- `CommunityRepository`의 `incrementLikeCount`/`decrementLikeCount` 호출하여 카운트 업데이트.
- 최종 '좋아요' 상태 (`boolean`)를 반환.
- `@Transactional` 적용.
- **`LikeController.java` (Controller 리팩토링):**
- 기존 `POST /like`, `DELETE /like` 엔드포인트 로직 통합 및 수정.
- 단일 `POST …
> [refactor] '좋아요' 기능 API 방식 리팩토링

- src/main/java/com/team05/linkup/domain/community/api/LikeController.java
- src/main/java/com/team05/linkup/domain/community/domain/Like.java
- src/main/java/com/team05/linkup/domain/community/infra/LikeRepository.java
- `LikeRepository`에 사용자 및 커뮤니티 ID 기반 '좋아요' 존재 확인 메소드를 추가했습니다.
- `LikeController`의 API 경로 및 Swagger 태그를 수정했습니다.
- `Like` 엔티티의 ID 생성 전략을 표준 JPA 방식으로 리팩토링했습니다.
- **`LikeRepository.java`:**
- `boolean existsByUserAndCommunityId(User user, String communityId)` 메소드를 추가하여, 특정 사용자와 게시글 ID에 대한 '좋아요' 존재 여부를 효율적으로 확인할 수 있는 기능을 추가했습니다.
- **`LikeController.java`:**
- API 기본 경로를 `/v1/community/{communityId}/like` 에서 `/v1/community/details/{communityId}/like` 로 변경하여 경로 구조를 수정했습니다.
- Swagger 문서 태그(`@Tag`)의 이름을 "Like API"에서 "커뮤니티 API"로 변경했습니다.
- **`Like.java` (Entity):**
- ID 필드(`id`)의 UUID 생성 전략을 Hibernate 특정 방식(`@UuidGenerator`)에서 표준 JPA 방식(`@GeneratedValue(strategy = GenerationType.UUID)`)으로 변경하여 코드를 표준화하고 단순화했습니다.
>  [refactor] '좋아요' 기능 리팩토링

- src/main/java/com/team05/linkup/domain/community/api/BookmarkController.java
- src/main/java/com/team05/linkup/domain/community/application/BookmarkService.java
- src/main/java/com/team05/linkup/domain/community/domain/Bookmark.java
- src/main/java/com/team05/linkup/domain/community/dto/BookmarkStatusResponse.java
- src/main/java/com/team05/linkup/domain/community/infra/BookmarkRepository.java
- 커뮤니티 게시글에 대한 **북마크(Bookmark) 토글 기능**을 신규 구현했습니다. (API, Service, Repository, Entity, DTO 포함)
**1. 북마크(Bookmark) 기능 신규 구현:**
- **`Bookmark.java` (Entity):**
- 사용자와 커뮤니티 게시글 간의 북마크 관계를 정의하는 엔티티 추가 (`User`, `Community`와 ManyToOne, UUID PK).
- **`BookmarkRepository.java` (Repository):**
- `JpaRepository`를 상속받는 북마크 리포지토리 추가.
- `existsByUserAndCommunityId`, `findByUserAndCommunityId` 쿼리 메소드 포함.
- **`BookmarkService.java` (Service):**
- `@Transactional` 기반의 북마크 토글 로직 구현 (기존 북마크 확인 후 생성 또는 삭제).
- **`BookmarkController.java` (Controller):**
- `POST /v1/community/details/{communityId}/bookmark` 엔드포인트 추가.
- `BookmarkService`를 호출하여 토글 로직 실행 및 최종 상태(`BookmarkStatusResponse`) 응답.
- **`BookmarkStatusResponse.java` (DTO):**
- 북마크 토글 후 최종 상태(`boolean bookmarked`)를 담는 응답 DTO 추가.
---
> [feat] 북마크 토글 기능 구현

- src/main/java/com/team05/linkup/domain/user/api/ProfileController.java
- src/main/java/com/team05/linkup/domain/user/application/ProfileService.java
- src/main/java/com/team05/linkup/domain/user/dto/ActivityResponseDTO.java
- [✔️] 리팩토링
---
- 마이페이지 활동 내역 응답 구조를 기존 Map에서 DTO 기반 구조로 리팩토링
- Controller에서 서비스로 역할 분리
---
- 작업 1: `Map<String, Object>` → `ActivityResponseDTO`로 변경
- 작업 2: `ProfileService`에 `getCommonActivityDTO()` 메서드 분리
- 작업 3: `ActivityResponseDTO`에 `@Builder(toBuilder = true)` 추가
- 작업 4: `Controller`에서는 역할 분기 및 응답 빌딩만 처리하도록 변경
---
- [✔️] 코드 점검 완료
- [✔️] 테스트 통과
- [✔️] 문서/주석 최신화
---
> [refactor] ProfileController 역할 분기 외 로직 제거 및 응답 구조 Map → DTO 리팩토링

- src/main/java/com/team05/linkup/common/dto/UserPrincipal.java
- src/main/java/com/team05/linkup/common/filter/JwtAuthenticationFilter.java
- src/main/java/com/team05/linkup/domain/mentoring/api/AiMatchingController.java
- src/main/java/com/team05/linkup/domain/user/api/RoleController.java
- src/main/java/com/team05/linkup/domain/user/application/ModifyRoleServiceImpl.java
- src/main/java/com/team05/linkup/domain/user/infrastructure/UserRepository.java
- @AuthenticationPrincipal 개선
- 작업 1: 스프링 컨텍스트 홀더에 provider과 providerId를 추가해 UserPrincipal 을 레코드를 생성하고  JwtAuthenticationFilter에 해당 객체값을 등록 하여 캡슐화를 진행했습니다. 이후  @AuthenticationPrincipal 으로 해당 객체값을 들고와 Jwtutil로 claim을 검증하는 작업을 줄여 편의성을 높였습니다.
- (선택사항)
> [refactor] 유저 인증 객체 등록

- src/main/java/com/team05/linkup/domain/community/api/BookmarkController.java
- src/main/java/com/team05/linkup/domain/community/api/LikeController.java
- src/main/java/com/team05/linkup/domain/community/application/BookmarkService.java
- src/main/java/com/team05/linkup/domain/community/application/LikeService.java
- `@AuthenticationPrincipal`을 통해 주입받는 사용자 정보 객체를 `String`에서 `UserPrincipal`로 변경하여 명확성 및 안정성 개선
- **`UserPrincipal` 도입:**
- 인증된 사용자의 `provider` (e.g., "kakao", "google")와 `providerId`를 함께 가지는 `UserPrincipal` 레코드(또는 DTO)를 정의했습니다.
- (가정) `JwtAuthenticationFilter` 또는 관련 인증 필터에서 인증 성공 시, `SecurityContextHolder`에 `Authentication` 객체의 `principal`로서 `String` 대신 `UserPrincipal` 객체를 설정하도록 수정했습니다.
- **컨트롤러 변경 (`BookmarkController`, `LikeController`):**
- `@AuthenticationPrincipal String providerId` 대신 `@AuthenticationPrincipal UserPrincipal userPrincipal`을 사용하도록 변경했습니다.
- 컨트롤러 내부 로직에서 `userPrincipal.provider()` 와 `userPrincipal.providerId()`를 호출하여 필요한 값을 얻도록 수정했습니다.
- **서비스 계층 변경 (`BookmarkService`, `LikeService`):**
- `toggleBookmark`, `toggleLike` 메서드의 파라미터를 `String providerId`에서 `String provider, …
> [refactor] UserPrincipal 도입하여 사용자 식별 개선

- src/main/java/com/team05/linkup/domain/user/api/ProfileController.java
- src/main/java/com/team05/linkup/domain/user/application/ProfileService.java
- src/main/resources/application-prod.yml
- `isCurrentUser` 로직을 **provider와 providerId를 함께 비교**하도록 수정하여 정확한 사용자 확인
- **레이지 로딩 문제 해결**: `area`와 `sigungu` 데이터를 조회할 때 레이지 로딩으로 인한 성능 이슈 해결
- **`isCurrentUser` 로직 개선**: 
- 사용자의 **provider**와 **providerId**를 비교하여 현재 사용자와 일치하는지 확인하도록 수정했습니다. 이전에는 `providerId`만 비교했지만, 이제는 `provider`와 `providerId` 두 값을 함께 비교하여 더 정확한 일치 여부를 확인할 수 있습니다. 이를 통해 보안과 정확성을 강화하였습니다.
- **`@AuthenticationPrincipal`을 사용하여 로그인한 사용자 정보 조회**:
- **`ProfileController`** 에서 `getProfile` 메소드에 **`@AuthenticationPrincipal`** 을 추가하여 현재 로그인한 사용자의 정보를 **`userPrincipal`** 로 받아오도록 수정하였습니다.
- **트랜잭셔널 적용**:
- `getProfile` 메소드에 `@Transactional(readOnly = true)`를 적용하여 **`area`와 `sigungu` 데이터 조회 시 레이지 로딩 이슈**를 해결했습니다.
- 멘토/멘티 프로필 정상 조회 확인
- 로그인한 사용자가 자신의 프로필을 조회할 때 `isCurrentUser`가 true로 반환되는지 확인
- 시/군/구 정보가 정확하게 조회되는지 확인 완료
> [fix] 프로필 lazy loading 문제(지역/시군구 조회) 해결 및 현재 사용자 식별 로직 정확성 개선

- .github/workflows/deploy-to-oci.yml
- build.gradle
- GitHub Actions 빌드 실패 원인인 Supabase 라이브러리 인증(401) 문제 해결
- GitHub Packages 접근 권한(`permissions.packages: read`) 추가
- CI workflow 파일 (`deploy-to-oci.yml`)에 `permissions` 블록 추가  
```yaml
permissions:
packages: read
contents: read
```
* 더 이상 `gradle.properties` 내 GPR 사용자/토큰 정보 불필요
* GitHub Actions 빌드 환경에서만 자동 인증이 적용됨
→ 로컬 개발 시에는 환경변수 또는 개인 `~/.gradle/gradle.properties` 유지 필요
* 참고: [https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions)
> [ci] GitHub Actions에서 Supabase 라이브러리 인증 오류 해결 및 GPR 접근 권한 설정

- src/main/java/com/team05/linkup/domain/mentoring/dto/MatchedMentorProfileDto.java
- src/main/java/com/team05/linkup/domain/mentoring/infrastructure/MentoringRepository.java
- src/main/java/com/team05/linkup/domain/user/api/ProfileController.java
- src/main/java/com/team05/linkup/domain/user/application/MenteeProfileService.java
-   **멘티 사용자가 신청한 매칭 목록을 페이징하여 조회**하는 기능 추가 (나의 활동 내역 more-details)
-   신청한 매칭 목록 조회 시, **멘토 정보에 `contactLink`를 포함**하도록 수정
-   페이징된 매칭 세션을 조회하기 위해 `MentoringRepository`에 새로운 쿼리 메소드(`findByMenteeUserIdPaged`) 추가
-   `ProfileController`에 "나의 활동 내역 more-details" 엔드포인트(`GET /v1/users/{nickname}/activity/more-details`)에서 `type=my-matches`를 처리하는 로직 추가
-   `MenteeProfileService`에서 페이징된 매칭 데이터를 조회하고 DTO로 변환하는 로직 구현
-   `MatchedMentorProfileDto.MentorDto`에 `contactLink` 필드 추가
*   **API**: `GET /v1/users/{nickname}/activity/more-details?type=my-matches`
*   **기능**: 특정 멘티 사용자가 신청한 멘토링 세션 목록을 페이징하여 상세 조회합니다.
*   **구현**:
*   `ProfileController`에 `getActivityMoreDetails` 메소드를 통해 요청을 처리하도록 추가되었습니다.
*   `type` 파라미터가 `my-matches`일 경우, `MenteeProfileService`의 `getMyMatchesPaged` 메소드를 호출합니다.
* …
> [feat] 나의 활동 내역 조회 more-details (내가 신청한 매칭) 기능 추가 및 멘토 연락 링크 포함

- src/main/java/com/team05/linkup/domain/community/api/BookmarkController.java
- src/main/java/com/team05/linkup/domain/community/api/CommunityController.java
- src/main/java/com/team05/linkup/domain/community/api/LikeController.java
- src/main/java/com/team05/linkup/domain/community/application/CommunityService.java
- src/main/java/com/team05/linkup/domain/community/dto/BookmarkStatusResponseDTO.java
- src/main/java/com/team05/linkup/domain/community/dto/CommunitySummaryResponseDTO.java
- src/main/java/com/team05/linkup/domain/community/dto/CommunityWeeklyPopularDTO.java
- src/main/java/com/team05/linkup/domain/community/dto/LikeStatusResponse.java
- src/main/java/com/team05/linkup/domain/community/dto/LikeStatusResponseDTO.java
- src/main/java/com/team05/linkup/domain/community/infrastructure/CommunityRepository.java
커뮤니티의 주간 인기 게시글을 조회하는 기능을 새롭게 추가하고, 기존 DTO 클래스들의 명칭을 일관성 있게 변경했습니다. 또한, `CommunitySummaryResponseDTO`에 `content`와 `profileImageUrl` 필드를 추가하여 게시글 요약 정보의 상세성을 높였습니다.
1.  **주간 인기 게시글 조회 기능 추가 (`/v1/community/weekly-popular`)**
* **API:** `GET /v1/community/weekly-popular`
* **기능:** 최근 `day`일 동안 작성된 게시글 중 조회수, 좋아요 수, 최신순으로 정렬된 상위 `limit`개의 인기 게시글 목록(ID, 제목, 카테고리)을 조회합니다.
* **구현:**
* `CommunityController`: `getWeeklyPopularCommunities` 메소드 및 `@GetMapping("/weekly-popular")` 엔드포인트를 추가했습니다.
* `@RequestParam(defaultValue = "5") int limit`: 반환할 인기 게시물의 최대 개수입니다.
* `@RequestParam(defaultValue = "7") int day`: 인기도를 평가할 지난 일 수입니다.
* `CommunityService`: `findWeeklyPopularCommunities` 메소드를 구현했습니다.
* 조회 시작 시점(`ZonedDateTime.now().minusDays(day)`)을 계산합니다.
* 결과 개수 제한을 위한 `PageRequest.of(0, limit)`을 설정합니다. …
> [feat] 주간 인기 게시글 조회 기능 추가 & [refactor] DTO 클래스명 변경

- src/main/java/com/team05/linkup/common/enums/ResponseCode.java
- src/main/java/com/team05/linkup/common/util/ApiUtils.java
- src/main/java/com/team05/linkup/domain/community/api/AiCommentController.java
- src/main/java/com/team05/linkup/domain/community/application/AiCommentViewServiceImpl.java
- src/main/java/com/team05/linkup/domain/mentoring/api/AiMatchingController.java
- src/main/java/com/team05/linkup/domain/mentoring/application/AiMatchingListServiceImpl.java
- src/main/java/com/team05/linkup/domain/mentoring/application/AiMatchingSelectorServiceImpl.java
- src/main/java/com/team05/linkup/domain/mentoring/application/AiMatchingService.java
- src/main/java/com/team05/linkup/domain/mentoring/application/MatchingService.java
- src/main/java/com/team05/linkup/domain/mentoring/dto/AiMatchingRequestDTO.java
- src/main/java/com/team05/linkup/domain/user/api/AuthController.java
- src/main/java/com/team05/linkup/domain/user/api/RoleController.java
- src/main/java/com/team05/linkup/domain/user/infrastructure/UserRepository.java
- 로그인 시 프론트 응답결과 추가
- 컨트롤러 응답 결과 통일
- 작업 1: 로그인시 루트 경로로 리다이렉트 되어 프론트에 명시적으로 /session-info api를 호출하여  응답 결과를 받을 수 있도록 기능을 추가했습니다
- 작업 2: 컨트롤러 응답 결과를 통일 했습니다
- (선택사항)
> [feat] 로그인 응답결과 기능 && [refactor] 컨트롤러 응답 결과 개선

- src/main/java/com/team05/linkup/domain/baseEntity/BaseEntity.java
- src/main/java/com/team05/linkup/domain/community/api/CommunityController.java
- src/main/java/com/team05/linkup/domain/community/application/CommunityService.java
- src/main/java/com/team05/linkup/domain/community/domain/Community.java
- src/main/java/com/team05/linkup/domain/community/domain/Tag.java
- src/main/java/com/team05/linkup/domain/community/dto/CommunityDto.java
- src/main/java/com/team05/linkup/domain/community/dto/TagDTO.java
- src/main/java/com/team05/linkup/domain/community/infrastructure/CommunityRepository.java
- src/main/java/com/team05/linkup/domain/community/infrastructure/CommunityRepositoryCustom.java
- src/main/java/com/team05/linkup/domain/community/infrastructure/CommunityRepositoryCustomImpl.java
- src/main/java/com/team05/linkup/domain/community/infrastructure/TagRepository.java
이번 PR에서는 `BaseEntity`에 대한 Javadoc을 추가하여 문서화를 개선하고, 고유하고 재사용 가능한 태그를 관리하기 위한 `Tag` 엔티티를 추가했습니다. 
또한, `Community` 엔티티와 `Tag` 엔티티 간의 다대다 관계를 구현하고, 관련 DTO 및 Repository를 조정하여 다중 태그 기능을 지원하도록 리팩토링했습니다. (community 테이블 삭제 or ddl-auto: create-drop 설정)
더불어, 새로운 태그 구조에 맞춰 사용자 지정 쿼리를 업데이트하고, 태그 관리 로직을 서비스 레이어에 통합했으며, API 레이어에서 게시글 생성/수정 시 `providerId` 대신 `UserPrincipal`을 사용하도록 변경했습니다. 
마지막으로, 커뮤니티 인기 태그 조회 및 태그 필터링 기능을 추가했습니다.
1.  **`docs: BaseEntity`에 대한 Javadoc 추가**
* `com.team05.linkup.domain.baseEntity.BaseEntity` 클래스에 대한 Javadoc을 추가하여 해당 엔티티의 역할과 필드에 대한 설명을 제공했습니다. 이는 코드의 가독성을 높이고 유지보수를 용이하게 합니다.
2.  **`feat: 고유하고 재사용 가능한 태그를 관리하기 위한 태그 엔티티 추가`**
* `com.team05.linkup.domain.community.domain.Tag` 엔티티를 새로 추가하여 커뮤니티 게시글에 태그를 연결하고 관리할 수 있도록 했습니다.
* `name` 필드를 통해 태그의 고유성을 보장하고, `communities` 필드를 통해 …
> [feat] Community 엔티티와 Tag 엔티티 간의 다대다 관계 구현, 인기 태그 조회 및 태그 필터링 기능 추가 & [refactor]  관련 DTO 및 Repository 조정

- src/main/java/com/team05/linkup/domain/community/dto/CommunityTalentSummaryDTO.java
- src/main/java/com/team05/linkup/domain/community/infrastructure/CommunityRepository.java
- src/main/java/com/team05/linkup/domain/user/api/ProfileController.java
- src/main/java/com/team05/linkup/domain/user/application/InterestMoreDetailsService.java
- src/main/java/com/team05/linkup/domain/user/application/MentorProfileService.java
- src/main/java/com/team05/linkup/domain/user/application/ProfileService.java
- src/main/java/com/team05/linkup/domain/user/dto/ActivityMoreDetailsResponseDTO.java
- src/main/java/com/team05/linkup/domain/user/dto/ActivityResponseDTO.java
- src/main/java/com/team05/linkup/domain/user/dto/MyCommentResponseDTO.java
- src/main/java/com/team05/linkup/domain/user/dto/MyPostResponseDTO.java
- 마이페이지 more-details API 전반에 me, type, content 구조 적용
- 게시글/댓글/재능/관심목록 API 통합 구조 정리 및 UI 연동 필드 추가
- 기존 응답 구조 개선 및 JavaDoc 문서 추가
- 공통 응답 구조 개선
- ActivityMoreDetailsResponseDTO<T> 공통 래퍼 DTO 생성
→ 모든 more-details 응답에 me, type, content 포함하도록 변경
- 기존에 Page<T>로 반환되던 응답 → 래핑 구조로 통일 (프론트 구분 로직 개선 목적)
- 본인 여부(me) 판단 로직 추가
- UserPrincipal을 활용한 me 여부 판별 로직 도입 (nickname 비교)
- ProfileController 내부 모든 more-details API에 적용 완료
- 관심 목록 more-details API 리팩토링
- /v1/users/{nickname}/activity/more-details/interests
- filter=bookmarked|liked|all 적용 시 분기 처리
- 북마크 / 좋아요 DTO 통합 래핑 구조 적용
- DTO 내부에 type, updatedAt, title, content 필드 명확화
- 게시글 / 댓글 more-details 개선
- 게시글 DTO에 postId 필드 추가 (상세페이지 이동용)
- 댓글 DTO에 postUri 필드 추가 (상세페이지 링크용)
- category → categoryDisplayName 필드 추가 및 한글 변환 적용
-  재능 목록 more-details 개선
- 기존 …
> [feat] 마이페이지 More Details 전체 API(me/type) 구조 통합 및 재능 목록 기능 개선

- src/main/java/com/team05/linkup/domain/user/application/ProfileService.java
- src/main/java/com/team05/linkup/domain/user/dto/ProfileSettingsResponseDTO.java
- 프로필 설정 조회 API (`GET /v1/users/{nickname}/profile`)에 displayName 필드 추가
- 시군구 코드(sigunguCode) 외에 시군구 한글명(sigunguName) 응답 추가
- 프론트에서 enum code만 받아도 한글로 표시 가능하도록 displayName 필드 제공
- 시군구도 마찬가지로 code + name 함께 응답
- 기존 PATCH 요청 구조(`code` 기반)는 그대로 유지, **프론트에서 displayName → code 매핑 처리 필요**
- 구조적 리팩토링은 추후 `EnumResponseDTO<T>` 등으로 개선 가능
- 구조적 리팩토링은 추후 `EnumResponseDTO<T>` 등으로 개선 가능
- 프론트에서 displayName을 표기하고 code로 전송하면 그대로 백엔드에서 enum으로 매핑됨
> [feat] 프로필 설정 응답에 displayName 및 시군구 한글명 추가

- src/main/java/com/team05/linkup/domain/user/application/ProfileService.java
- src/main/java/com/team05/linkup/domain/user/dto/ProfileSettingsResponseDTO.java
- 프로필 설정 조회 응답에 areaCode(지역 코드) 필드 추가
- GET /v1/users/{nickname}/profile 응답에 지역 코드(areaCode) 필드 추가
- 기존에는 지역명(area)만 존재하여 프론트에서 코드 매핑이 어려웠음
- areaName + areaCode를 함께 응답하도록 구조 개선
- 관련 DTO(ProfileSettingsResponseDTO) 및 서비스(ProfileService) 로직 수정
> [feat] 프로필 설정 응답에 areaCode 필드 추가

- src/main/java/com/team05/linkup/domain/user/api/LoginUserInfoController.java
- src/main/java/com/team05/linkup/domain/user/dto/LoginUserInfoDTO.java
- 현재 로그인한 유저의 nickname, role을 반환하는 API 추가
- `/v1/users/me` GET 엔드포인트 구현
- `LoginUserInfoController`, `LoginUserInfoDTO` 추가
- JWT 기반 로그인 세션에서 사용자 식별 후 nickname/role 응답
- Swagger에서 정상 응답 확인
> [feat] 로그인 유저 정보 조회 API 구현 (/v1/users/me)

- src/main/java/com/team05/linkup/domain/user/api/LoginUserInfoController.java
- /v1/users/me → /v1/authUser/me로 API 경로 분리
- 작업 1: 기존 로그인 사용자 정보 조회 API에서 TEMP 유저 접근 문제로 인해 경로 분리
- 작업 2: 시큐리티 설정을 유지하면서 TEMP 유저도 접근 가능하도록 /v1/authUser/me로 이동 처리
> [refactor] 기존 /v1/users/me → /v1/authUser/me 로 경로 분리

- src/main/java/com/team05/linkup/domain/community/api/BookmarkController.java
- src/main/java/com/team05/linkup/domain/community/api/CommunityController.java
- src/main/java/com/team05/linkup/domain/community/api/LikeController.java
- src/main/java/com/team05/linkup/domain/community/application/BookmarkService.java
- src/main/java/com/team05/linkup/domain/community/application/CommunityService.java
- src/main/java/com/team05/linkup/domain/community/application/LikeService.java
- src/main/java/com/team05/linkup/domain/community/dto/LikeResponseDTO.java
- src/main/java/com/team05/linkup/domain/community/dto/LikeStatusResponseDTO.java
- src/main/java/com/team05/linkup/domain/community/infrastructure/LikeRepository.java
- 커뮤니티 기능(좋아요, 북마크, 상세 조회) 전반에 걸쳐 사용자 인증 정보(`UserPrincipal`) 처리 방식을 표준화했습니다.
- 좋아요 기능 실행 시, 게시글의 최신 좋아요 수를 함께 반환하도록 개선했습니다.
- 게시글 상세 조회 시, 현재 사용자의 좋아요 및 북마크 상태를 표시하도록 기능을 추가했습니다.
- API 응답 정책을 통일하여, 모든 응답(성공/실패)에 대해 HTTP 상태 코드 200을 반환하고 본문에서 처리 결과를 명시하도록 변경했습니다.
- **작업 1: UserPrincipal 처리 표준화 (리팩토링)**
- `LikeService`, `BookmarkService`, `CommunityService`의 관련 메서드들이 `provider`, `providerId` 대신 `UserPrincipal` 객체를 직접 받도록 시그니처를 변경했습니다.
- `LikeController`, `BookmarkController`, `CommunityController`에서 사용자 정보를 추출하는 로직을 제거하고, `UserPrincipal` 객체를 서비스 계층으로 바로 전달하도록 수정하여 컨트롤러 로직을 단순화했습니다.
- **작업 2: 좋아요 기능 개선 (기능 추가)**
- `LikeService#toggleLike` 메서드가 `boolean` 대신 `LikeResponseDTO`를 반환하도록 변경했습니다.
- `LikeResponseDTO`는 사용자의 최종 `liked` 상태와 게시글의 업데이트된 `likeCount`를 포함합니다.
- 이를 통해 클라이언트가 좋아요 토글 후 별도 API 호출 …
> [feat] 좋아요 수 반환, 상세 상태 표시 및 UserPrincipal/응답 처리 개선

- src/main/java/com/team05/linkup/domain/community/domain/Community.java
- content 컬럼 타입(크기) 변경 tinytext -> text
- mysql에서 @Lob 단독 설정은 tinytext(255byte) 타입으로 설정되서 게시글 내용 저장에 문제 발생
- 65,535바이트인 text + @Lob으로 변경
> [fix] 게시글(community) content 컬럼 타입(크기) 변경 tinytext -> text

- src/main/java/com/team05/linkup/domain/community/infrastructure/CommunityRepository.java
- src/main/java/com/team05/linkup/domain/community/infrastructure/CommunityRepositoryCustom.java
- src/main/java/com/team05/linkup/domain/community/infrastructure/CommunityRepositoryCustomImpl.java
- src/main/java/com/team05/linkup/domain/user/api/ProfileController.java
- src/main/java/com/team05/linkup/domain/user/application/MatchingPageFacade.java
- src/main/java/com/team05/linkup/domain/user/application/MentorProfileService.java
- src/main/java/com/team05/linkup/domain/user/application/ProfileService.java
- src/main/java/com/team05/linkup/domain/user/dto/InterestCountDTO.java
- 마이페이지 게시글 필터 기능 추가 및 QnA 관심 태그 기반 추천 로직 리팩토링
- 작업 1: QnA 추천 로직에서 Interest enum 기반 추천 제거 → profileTag 기반 태그 매칭으로 변경
- 작업 2: 게시글 조회 시 filter 파라미터 유효성 검사 및 ALL 분기 처리 추가
- 게시글 필터에서 TALENT는 제외되며, 허용값은 all, QUESTION, INFO, REVIEW, FREE 입니다.
(필터링 기능은 my-posts에만 추가)
> [feat] 마이페이지 게시글 카테고리 필터 기능 및 QnA 관심 태그 기반 추천 로직 리팩토링

- src/main/java/com/team05/linkup/common/config/SecurityConfig.java
- src/main/java/com/team05/linkup/domain/mentoring/infrastructure/MentoringRepository.java
- src/main/java/com/team05/linkup/domain/review/api/MenteeReviewController.java
- src/main/java/com/team05/linkup/domain/review/application/ReviewService.java
- src/main/java/com/team05/linkup/domain/review/dto/ReviewResponseDTO.java
- src/main/java/com/team05/linkup/domain/review/dto/ReviewUpdateDTO.java
-   [x] 기능 개선
-   [ ] 버그 수정
-   [ ] 리팩토링
-   [ ] 문서 수정
-   [ ] 기타
-   **작성 가능한 멘토링 세션 목록 조회 기능 개선**: 멘티가 리뷰를 작성할 수 있는 **리뷰가 작성되지 않은 멘토링 세션 목록만 조회**하도록 개선했습니다.
-   **멘티 리뷰 작성 기능 추가**: 멘토링 세션 완료 상태 확인 및 리뷰 **중복 작성을 검증**하는 로직을 포함하여 리뷰 작성 기능을 구현했습니다.
-   **기존 리뷰 정보 수정/조회 기능 추가**: 특정 리뷰를 수정하기 위해 조회할 때 해당 리뷰의 **소유권을 확인**하는 로직을 포함했습니다. `ReviewResponseDTO`에 `reviewId`, `mentorName`, `profileImageUrl` 필드가 추가되었습니다.
-   **작성된 멘티 리뷰 수정 기능 추가**: 리뷰 수정 시 **소유권 및 입력 데이터의 유효성을 검증**하며, 기존 리뷰의 ID를 유지하면서 내용을 업데이트합니다. 요청 DTO가 `ReviewRequestDTO`에서 `ReviewUpdateDTO`로 변경되었습니다.
-   **작성된 멘티 리뷰 삭제 기능 추가**: 리뷰 삭제 시에도 해당 리뷰의 **소유권을 확인**하는 로직을 포함했습니다.
-   **특정 사용자의 멘티 리뷰 내역 조회 기능 추가**: 리뷰 내역 조회 시 **조회 권한을 확인**하고, N+1 문제를 방지하기 위한 쿼리 최적화(`findByMenteeIdWithMentorAndMentee`, `findByMentoringSessionIdIn`)를 적용했습니다. 조회된 …
> [fix] 리뷰 관련 API 수정, 요청/응답 DTO 수정

- src/main/java/com/team05/linkup/domain/community/application/CommunityService.java
- src/main/java/com/team05/linkup/domain/community/domain/AiComment.java
- src/main/java/com/team05/linkup/domain/community/domain/Community.java
- src/main/java/com/team05/linkup/domain/community/infrastructure/BookmarkRepository.java
- src/main/java/com/team05/linkup/domain/community/infrastructure/CommentRepository.java
- src/main/java/com/team05/linkup/domain/community/infrastructure/LikeRepository.java
- **게시글 삭제 시 연관 데이터 처리 개선**: 게시글(Community) 삭제 시 관련 댓글(Comment)이 누락되던 문제를 해결하고, AI 댓글(AiComment) 삭제 방식을 JPA Cascade로 변경하여 이전에 발생하던 `TransientObjectException`을 해결했습니다. 이를 통해 데이터 정합성 및 삭제 기능의 안정성을 확보했습니다.
- **문제점**: `Comment` 엔티티는 `communityId`를 `String` 타입 필드로 직접 참조하고 있어, 게시글 삭제 시 JPA Cascade의 자동 삭제 대상이 아니었습니다. 이로 인해 게시글만 삭제되고 댓글 데이터는 DB에 남아있는 문제가 발생했습니다.
- **해결 방안**:
- `CommentRepository`에 `deleteAllByCommunityId(String communityId)` 메소드 (JPQL `DELETE FROM Comment c WHERE c.communityId = :communityId`)를 추가했습니다.
- `CommunityService`의 `deleteCommunity` 메소드 내에서, 게시글을 삭제하기 전에 `commentRepository.deleteAllByCommunityId()`를 호출하여 해당 게시글에 연결된 모든 댓글을 명시적으로 삭제하도록 수정했습니다.
- **문제점**: 이전 게시글 삭제 로직 수행 중 간헐적으로 `TransientObjectException`이 발생했으며, `AiComment`의 명시적 삭제 로직이 복잡성을 더할 수 있었습니다.
- **해결 방안**:
- …
> [fix] 게시글 삭제 시 모든 연관 데이터(댓글, AI댓글 등) 정상 삭제되도록 수정
